#include <stdio.h>          //including necessary libraries and the header
#include <stdlib.h>
#include "header.h"         
struct Player{              //structing the player and initializing the structure members
    int positionx;          //x position of the sturcture
    int positiony;          //y position of the structure
    int character;};        //character of the structure
struct Player player1;      //declaring player 1 
struct Player player2;      //declaring player 2
int Move(int dicenum, struct Player *player){                //The function required to move the players
        generateGrid();                                            //The 'generategrid function is called to make sure the foundational grid stays the same as the players move along the grid
        if((player->positiony + dicenum) <= 99){                   //Checking if any of the players are exceeding the grid limits
            player->positiony += dicenum ;                         //As long as players are not exceeding limits, the dice value is added to player positions
            array[player->positionx][player->positiony] = player->character;        //The new position of the player is replaced with the player characters which are ASCII characters
            printf("\nPosition on board: %d\n", player->positiony+1);               //Position on board is printed on the command window
            if (player->character == player1.character){                            //If player 1 has moved, make sure other player's character is also displayed on the grid
            array[player2.positionx][player2.positiony] = player2.character;
            }else{                                                                  //Similarly, if player 2 has moved, make sure other player's character is also displayed on the grid
                array[player1.positionx][player1.positiony] = player1.character;}   
                printGrid();}
        else{                                                                  //When the addition of the player position and the dice number exceeds grid limits, the player doesn't move
            array[player->positionx][player->positiony] = player->character;   //There is no change to player position
            printf("\nPosition on board: %d\n", player->positiony+1);
            if (player->character == player1.character){                        //If player 1 has moved, make sure other player's character is also displayed on the grid
            array[player2.positionx][player2.positiony] = player2.character;
            }else{                                                              //Similarly, if player 2 has moved, make sure other player's character is also displayed on the grid
            array[player1.positionx][player1.positiony] = player1.character;}
            printGrid();}}

int main(){

    srand(time(NULL)); //Setting the starting point to produce random numbers

    //Set of print functions are called to intialize the game
    printf("Welcome to Snakes and Ladders!\n\n");
    printf("Here are some rules: \n\n-Enter your player number to roll the dice, \nyou can't change your player number once you enter your name for the respective player.\n\n-Both players roll the dice. the one with the highest number starts the game.If both players roll the same number, \nthe program will roll the dice for both player automatically.\n-When you come across the ladder, it will take your from position 24 to 74 on the board.\n\n-When you coma across the snake, it will take you from position 86 to 50 on the board.\n\n-You can't finish the game if the number your roll exceeds the position 100 on the board, \nyou need to keep rolling till you get to 100!\n\n-One last thing! When you are at the same position with the other player, your player symbol might disappear.\nIt will reappear in the next turn.\n\nEnjoy the Game!\n\n");
    printf("------------------------------------------------------------------\n");
    printf("\nPlayer 1, enter your name: ");        
    gets(p1);                                   //Player 1 name is stored in the string variable 'p1'
    printf("\nPlayer 2, enter your name: ");
    gets(p2);                                   //Player 2 name is stored in the string variable 'p2'
    printf("\nNow enter your player number to roll the dice: ");
    scanf("%d", &playernumber); //Playernumber is stored to the adress of the variable 'playernumber'

    generateGrid();             //Grid is generated by calling the 'generateGrid' function
    init();                     //The game is initialized by calling the 'init' function

    player1.positionx= 0;       //Structure variable determining the x position of player 1 is set to 0
    player1.positiony= 0;       //Structure variable determining the y position of player 1 is set to 0
    player1.character= 219;     //Structure variable determining the character of player 1 set to to the ASCII character 219

    player2.positionx = 0;      //Structure variable determining the x position of player 2 is set to 0
    player2.positiony = 0;      //Structure variable determining the y position of player 2 is set to 0
    player2.character = 176;    //Structure variable determining the charaacter of player 2 is set to 0

    while(player1.positiony !=99 && player2.positiony != 99){           //As long as any of the players haven't completed the game, running the loop
        printf("\n------------------------------------------------------------------\n"); //Making it easier to follow the game on the command window
        if(loop()){             //Calling the loop function which returns 1 if it's player1's turn to player
            Move(player1dice, &player1);                                                //Calling the 'move' function to move the first player
            printf("\nPlayer 1: %d times    Player 2: %d times\n", counter1, counter2); //Printing the number of times both player have rolled dices
            if(player1.positiony == 23){                                                //Checking if player 1 has arrived at the ladder
                printf("\nLADDER!\n");                                                  //Informing the user that they have arrived at the ladder on the command window
                player1.positiony = 73;                                                 //Transferring the position of player 1 to 73
                array[player1.positionx][player1.positiony] = player1.character;        //Updating the position of player 1
                Move(0, &player1);                                                      //Moving player 1 by calling the 'move' function
                printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);}  //Printing the number of times both player have rolled dices
            else if(player1.positiony == 85){                                           //Checking if player 1 has arrived at the snake
                printf("\nSNAKE!\n");                                                   //Informing the user that they have arrived at the snake on the command window
                player1.positiony = 49;                                                 //Transferring the position of player 1 to 49
                array[player1.positionx][player1.positiony] = player1.character;        //Updating the position of player 1
                Move(0, &player1);                                                      //Moving player 1 by calling the 'move' function
                printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);} //Printing the number of times both player have rolled dices
            while (player1dice == 6){                                       //As long as player 1 rolls 6, they keep on rolling
                printf("\nYou rolled a 6 %s, roll again!\n", p1);           //Informing the user that they have rolled a 6 by printing it on the command window
                loop();                                                     //The function 'loop' is called to enable user to roll the dice again
                Move(player1dice, &player1);                                //The 'move' function is called to move the position of player 1
                printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2); //Printing the number of times both player have rolled dices
                if(player1.positiony == 23){                                //When player 1 rolls a 6, the program checks again whether if they have arrived at the ladder
                    printf("\nLADDER!\n");                                  //Informing the user that they have arrived at the ladder on the command window
                    player1.positiony = 73;                                 //Transferring the position of player 1 to 73
                    array[player1.positionx][player1.positiony] = player1.character;    //Updating the position of player 1
                    Move(0, &player1);                                                  //Moving player 1 by calling the 'move' function
                    printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);}  //Printing the number of times both player have rolled dices
                else if(player1.positiony == 85){   //Checking if player 1 has arrived at the snake
                    printf("\nSNAKE!\n");           //Informing the user that they have arrived at the snake on the command window
                    player1.positiony = 49;         //Transferring the position of player 1 to 49
                    array[player1.positionx][player1.positiony] = player1.character;    //Updating the position of player 1
                    Move(0, &player1);              //Moving player 1 by calling the 'move' function          
                    printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);}}} //Printing the number of times both player have rolled dices
        else{                                       //The 'loop' function returns 0 when it is player 2's turn to roll the dice
            Move(player2dice, &player2);            //Calling the 'move' function to move the second player       
            printf("\nPlayer 1: %d times    Player 2: %d times\n", counter1, counter2); //Printing the number of times both player have rolled dices
            if(player2.positiony == 23){                                                //Checking if player 2 has arrived at the ladder
                printf("\nLADDER!\n");                                                  //Informing the user that they have arrived at the ladder on the command window
                player2.positiony = 73;                                                 //Transferring the position of player 2 to 73
                array[player2.positionx][player2.positiony] = player2.character;        //Updating the position of player 2
                Move(0, &player2);                                                      //Moving player 2 by calling the 'move' function
                printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);} //Printing the number of times both player have rolled dices
            else if(player2.positiony == 85){                                           //Checking if player 2 has arrived at the snake
                printf("\nSNAKE!\n");                                                   //Informing the user that they have arrived at the snake on the command window
                player2.positiony = 49;                                                 //Transferring the position of player 2 to 49
                array[player2.positionx][player2.positiony] = player2.character;        //Updating the position of player 2
                Move(0, &player2);                                                      //Moving player 2 by calling the 'move' function
                printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);} //Printing the number of times both player have rolled dices
            while(player2dice == 6){                        //As long as player 2 rolls 6, they keep on rolling
                printf("\nYou rolled a 6 %s, roll again!\n", p2);   //Informing the user that they have rolled a 6 by printing it on the command window
                loop();                                             //The function 'loop' is called to enable user to roll the dice again
                Move(player2dice, &player2);                        //The 'move' function is called to move the position of player 2
                printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2); //Printing the number of times both player have rolled dices
                if(player2.positiony == 23){    //When player 2 rolls a 6, the program checks again whether if they have arrived at the ladder
                    printf("\nLADDER!\n");      //Informing the user that they have arrived at the ladder on the command window
                    player2.positiony = 73;     //Transferring the position of player 2 to 73
                    array[player2.positionx][player2.positiony] = player2.character;    //Updating the position of player 2
                    Move(0, &player2);          //Moving player 2 by calling the 'move' function
                    printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);} //Printing the number of times both player have rolled dices
                else if(player2.positiony == 85){   //Checking if player 2 has arrived at the snake
                    printf("\nSNAKE!\n");           //Informing the user that they have arrived at the snake on the command window
                    player2.positiony = 49;         //Transferring the position of player 2 to 49
                    array[player2.positionx][player2.positiony] = player2.character;    //Updating the position of player 2
                    Move(0, &player2);               //Moving player 2 by calling the 'move' function
                    printf("\nPlayer 1 : %d times     Player 2: %d times\n", counter1, counter2);}}}} //Printing the number of times both player have rolled dices
    if(player1.positiony == 99){                            //If player 1 arrives at the finishing position,
        printf("\nThe winner is %s!\n", p1);                //The user is informed by printing on the command window.
    }else if(player2.positiony == 99){                      //If player 2 arrives at the finishing position, 
        printf("\nThe winner is %s!\n", p2);}               //The user is informed by printing on the command window.
        return 0;}